language: node_js
node_js:
    - "7.8.0"
sudo: false
cache:
  directories:
    - node_modules
script:
    - npm i
    - npm run build:prod
install:
    - npm i -g firebase-tools
after_success:
    - firebase deploy --only hosting --token $FIREBASE_TOKEN --non-interactive